### ISSUE TITLE
Create GPX files

### ISSUE THREAD

**Issue by amenk** [aimnadze/canmore-gporter-poi-reader#1]
Awesome work!
Did you consider writing GPX files from the POIs?

**Comment by aimnadze** [comment]
Hi, sorry for a late response.

Do you still need writing GPX files? It should be fairly simple to implement.

Cheers

**Comment by amenk** [comment]
thanks for the response. I am no longer using the device.

**Comment by aimnadze** [comment]
Me too. I lost the device recently.
Have a nice day!
